### ISSUE TITLE
Does simple-db-migrate support adding stored procedure?

### ISSUE THREAD

**Issue by weizhu-us** [guilhermechapiewski/simple-db-migrate#19]
In order for SP to work, I will need to set DELIMITER and the simple-db-migrate parser parses the string by ";" which won't work.
Also, it gives syntax error, even I put  
DELIMITER$$
by itself in the script.

simple_db_migrate.core.exceptions.MigrationException: error executing migration: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER$$' at line 1")

[ERROR DETAILS] SQL command was:
DELIMITER$$

**Comment by wandenberg** [comment]
Fixed on 1ef55b766764fbae191c0a60fab7ae84e9f36b5d
Take a look on the example on readme
