### ISSUE TITLE
Please add subdirectories support

### ISSUE THREAD

**Issue by vorozhko** [guilhermechapiewski/simple-db-migrate#28]
Keeping all migration files in the same folder make it hard to navigate over time.
Could you please add subdirectories support?

**Comment by wandenberg** [comment]
Hi @vorozhko 

you can organize your files in multiple folders and add them to your configuration file as said on documentation.

"The MIGRATIONS_DIR directive may have relative (from the location of this file) or absolute paths separated by ':' pointing to the migrations directories."

This resolve your issue?

**Comment by vorozhko** [comment]
Hi,
yes I know about that, but it is not what I wanted.
Instead of keeping all migration in 1 folder I want to separate them by 'task id', so it will be better organised. 
But, it is impossible for us to add all 'new' tasks folder into migration_dir, because each new deployment it is new list.

**Comment by wandenberg** [comment]
You can use the --db-migrations-dir option and pass a dynamic list.
Each db-migrate user will have different requirements. Someone could ask to not list files recursively.
So, as a tool, is better let each one decide how to use it when possible.
In your case you can do something like that

```
db-migrate -c project.conf --db-migrations-dir=`ls migrations_dir | tr '\n' ':'`
```
