### ISSUE TITLE
Please add support for '-' and '_'  in migration file names

### ISSUE THREAD

**Issue by vorozhko** [guilhermechapiewski/simple-db-migrate#29]
Current patter is not allowed any characters except \w+
<code>
MIGRATION_FILES_MASK = r"[0-9]{14}_\w+%s$" % MIGRATION_FILES_EXTENSION
<code>

Please add support for '-' and '_' in the file names.

**Comment by wandenberg** [comment]
The '_' is already supported with this regular expression.
Take a look on 'example' folder for some accepted names.

**Comment by vorozhko** [comment]
Yes, underscores is working, but we also want to have ticket id in the file name, but ticket id contain '-' in it. So, that limit will lead to human errors when somebody will forget to use underscores instead of minus in the file name as such files will be ignored.

**Comment by vorozhko** [comment]
Thanks for the fix. When fix will be released to be available by pip install?
