### ISSUE TITLE
Do not return Error if no migration files found

### ISSUE THREAD

**Issue by vorozhko** [guilhermechapiewski/simple-db-migrate#30]
I did get a message "[ERROR] no migration files found" and return code is 1.
But, it just does mean there was no migration needed.
Could you please change behaviour of this.

**Comment by wandenberg** [comment]
Hi @vorozhko 

could you explain what was the problem?

Run db-migrate command without any migration files, is in fact to be considered an execution error.
Run db-migrate with migration files already applied to your database, isn't.
This is the same approach of other commands, for instance

```
$ cp
cp: missing file operand
Try 'cp --help' for more information.

$ echo $?
1
```

**Comment by vorozhko** [comment]
The problem is when all migration files were executed on first run, next run db migrate return Error, however there was no actual errors, only no new migrations were added.

**Comment by wandenberg** [comment]
I think you are executing the program in a wrong way.
Here is an example of running db-migrate twice with the same files.
The first run it applied all migrations.
The second one it shows "Nothing to do." and ends with success.

```
$ db-migrate -c example/mysql/simple-db-migrate.conf 

Starting DB migration on host/database "localhost/migration_example" with user "root"...
- Current version is: 0
- Destination version is: 20090228235709

Starting migration up!
*** versions: ['20090123195634', '20090211120001', '20090211120001', '20090211120002', '20090211120003', '20090228235709']

===== executing 20090123195634_create_table_users.migration (up) =====
===== executing 20090211120001_add_user_address.migration (up) =====
===== executing 20090211120001_add_user_age.migration (up) =====
===== executing 20090211120002_add_user_mother_age.migration (up) =====
===== executing 20090211120003_create_table_chimps.migration (up) =====
===== executing 20090228235709_create_table_aleatory.migration (up) =====

Done.


$ db-migrate -c example/mysql/simple-db-migrate.conf 

Starting DB migration on host/database "localhost/migration_example" with user "root"...
- Current version is: 20090228235709
- Destination version is: 20090228235709

Nothing to do.


Done.


$ echo $?
0
```

**Comment by vorozhko** [comment]
Yes, right. Error happen only if directory has no files or files are not pass regex format of migration files.
