### ISSUE TITLE
Package is out of date, doesn't work with python 3

### ISSUE THREAD

**Issue by johnnymo87** [guilhermechapiewski/simple-db-migrate#34]
It looks like you all added python 3 support with this commit: https://github.com/guilhermechapiewski/simple-db-migrate/commit/8e721493aceb5b79d8e4f5edf24bf39608ab855d

However, when I install the package with `pip`, it looks like this code is not present.

```
Downloading simple-db-migrate-2.2.0.tar.gz (41kB)
  Complete output from command python setup.py egg_info:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-udo31o1j/simple-db-migrate/setup.py", line 2, in <module>
      import simple_db_migrate
    File "/tmp/pip-build-udo31o1j/simple-db-migrate/simple_db_migrate/__init__.py", line 95
      except Exception, e:
                      ^
  SyntaxError: invalid syntax
```

**Comment by wandenberg** [comment]
@johnnymo87 can you check if the code on branch [python3](https://github.com/guilhermechapiewski/simple-db-migrate/tree/python3) is OK?
Some tests did not run under python3.5 and I also had to change some code to properly work.

**Comment by wandenberg** [comment]
@johnnymo87 I updated the [python3](https://github.com/guilhermechapiewski/simple-db-migrate/tree/python3) branch. Now tests are running with `python 3.6` and `python 2.7`.
I only need another pair of eyes to check and merge the code to master.

**Comment by johnnymo87** [comment]
I'll give it a look!

**Comment by johnnymo87** [comment]
I'm not much of a pythonista, but the code in that branch looks good to me. I pulled it down locally and used it instead of my fork, and it worked fine.

**Comment by tarun29061990** [comment]
Facing this while doing pip install -r requirements.txt

```
Collecting git+https://github.com/guilhermechapiewski/simple-db-migrate@python3 (from -r requirements.txt (line 17))
  Cloning https://github.com/guilhermechapiewski/simple-db-migrate (to python3) to /private/var/folders/39/9z35vs0x5f38l9l3w6y9kcth0000gp/T/pip-cq1g9e55-build
  Could not find a tag or branch 'python3', assuming commit.
error: pathspec 'python3' did not match any file(s) known to git.
Command "git checkout -q python3" failed with error code 1 in /private/var/folders/39/9z35vs0x5f38l9l3w6y9kcth0000gp/T/pip-cq1g9e55-build
```

**Comment by wandenberg** [comment]
@tarun29061990 the `python3` branch was already merged on master and released to pypi. 
Update your requirements.txt.
I will close this issue now.
