### ISSUE TITLE
Type error in python 3.6

### ISSUE THREAD

**Issue by rajeev1982** [guilhermechapiewski/simple-db-migrate#38]
I get an error when I run migration in python-3.6

```
Traceback (most recent call last):
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/__init__.py", line 92, in run
    Main(config).execute()
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/main.py", line 50, in execute
    self._execution_log('\nStarting DB migration on host/database "%s/%s" with user "%s"...' % (self.config.get('database_host'), self.config.get('database_name'), self.config.get('database_user')), "PINK", log_level_limit=1)
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/main.py", line 254, in _execution_log
    CLI.msg(msg, color)
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/cli.py", line 243, in msg
    print("{}{}{}".format(cls.color[color], msg, cls.color["END"]))
  File "/Users/rajeev/Workspace/procure/procure-backend/bin/../lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rajeev/Workspace/procure/procure-backend/bin/db-migrate", line 11, in <module>
    sys.exit(run_from_argv())
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/__init__.py", line 18, in run_from_argv
    run(options.__dict__)
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/__init__.py", line 96, in run
    CLI.error_and_exit(str(e))
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/cli.py", line 233, in error_and_exit
    cls.msg("[ERROR] %s\n" % msg, "RED")
  File "/Users/rajeev/Workspace/procure/procure-backend/lib/python3.6/site-packages/simple_db_migrate/cli.py", line 243, in msg
    print("{}{}{}".format(cls.color[color], msg, cls.color["END"]))
  File "/Users/rajeev/Workspace/procure/procure-backend/bin/../lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by wandenberg** [comment]
Can you check how are set the configurations in your configuration file?
This line `self._execution_log('\nStarting DB migration on host/database "%s/%s" with user "%s"...' % (self.config.get('database_host'), self.config.get('database_name'), self.config.get('database_user')), "PINK", log_level_limit=1)` is execute only as a info log, but this means that it has something weird on your database name/user.
Probably a non ascii char making it be parsed as a byte array instead of a string.

**Comment by rajeev1982** [comment]
Here is my config file

# simple-db-migrate config file

DATABASE_HOST = "127.0.0.1"
DATABASE_USER = "root"
DATABASE_PASSWORD = ""
DATABASE_NAME = "procure_backend"

###############################################################################

# There is an alternative and convenient way to create your configuration
# files making it possible to override values. If you use 'os.getenv' like
# in the example below, you can pass value to override the default settings
# through the command line using:
#
# [shell]$ DATABASE_HOST='my.database.host' db-migrate (... parameters ...)
#
# The example above will override the DATABASE_HOST with 'my.database.host'
# instead of using 'localhost'.
#
# * Example of overridable config:
# DATABASE_HOST = os.getenv("DATABASE_HOST") or "localhost"
# DATABASE_USER = os.getenv("DATABASE_USER") or "root"
# DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD") or ""
# DATABASE_NAME = os.getenv("DATABASE_NAME") or "migration_example"

###############################################################################

# In some cases you will not want to write database passwords in the config
# files (e.g. production databases passwords). You can configure the password
# to be asked for you in the command line.
#
# DATABASE_PASSWORD = "<<ask_me>>"

###############################################################################

# Relative path from the location of this file.
# You can put multiple directories if you want, separated by ':'.
# The path can be absolute or relative (recommended).
#
# * Example:
# DATABASE_MIGRATIONS_DIR = os.getenv("MIG_DIR") or "./migrations/dir:./another/dir"

DATABASE_MIGRATIONS_DIR = "./db"

###############################################################################

# Script format
#
# UTC_TIMESTAMP = True will cause creation scripts to utilize a UTC timestamp
# instead of a local timestamp (default)
#
UTC_TIMESTAMP = os.getenv("UTC_TIMESTAMP") or True
force_execute_old_migrations_versions = True

**Comment by rajeev1982** [comment]
Even pip install simple-db-migrate==3.0.0 fails in 3.6.x. 

Any update on this bug?

**Comment by wandenberg** [comment]
Hi @rajeev1982. Do you mind to share your migrations/configuration with me?
If possible, in a virtual machine (like vagrant).
I just installed the package in a clean python 3.6 environment without errors.
```
simple-db-migrate$ python -V
Python 3.6.3
simple-db-migrate$ date
Mon Feb 19 00:06:21 CET 2018
simple-db-migrate$ pip install simple-db-migrate==3.0.0
Collecting simple-db-migrate==3.0.0
Installing collected packages: simple-db-migrate
Successfully installed simple-db-migrate-3.0.0
simple-db-migrate$ pip freeze
simple-db-migrate==3.0.0
simple-db-migrate$
```

**Comment by rajeev1982** [comment]
I am installing python from ubuntu ppa and its failing in that. I tested the same thing in a python docker image seems to be working. It might be the case that my python install has an issue.

Let me remove ubuntu ppa and install from downloaded image and try. Will update after that.

**Comment by rajeev1982** [comment]
Looks like the problem is LC_CTYPE. I added the below export in my bash profile and the problem seems to be resolved.

export LC_CTYPE=UTF-8

**Comment by rajeev1982** [comment]
Try this if above doesn't work

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by rajeev1982** [comment]
This does not work again in python 3.8. Here is the error

$ docker run -it python:3.8 /bin/bash
root@4f07de037284:/# python --version
Python 3.8.2
root@4f07de037284:/# pip install simple-db-migrate
Collecting simple-db-migrate
  Downloading simple-db-migrate-3.0.0.tar.gz (42 kB)
     |████████████████████████████████| 42 kB 402 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6peapnk/simple-db-migrate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k6peapnk/simple-db-migrate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-k6peapnk/simple-db-migrate/pip-egg-info
         cwd: /tmp/pip-install-k6peapnk/simple-db-migrate/
    Complete output (21 lines):
    /tmp/pip-install-k6peapnk/simple-db-migrate/simple_db_migrate/main.py:136: SyntaxWarning: "is not" with a literal. Did you mean "!="?
      if destination_version is not '0' and not (self.db_migrate.check_if_version_exists(destination_version) or self.sgdb.get_version_id_from_version_number(destination_version)):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k6peapnk/simple-db-migrate/setup.py", line 4, in <module>
        setup(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 982, in run_command
        log.info("running %s", command)
      File "/usr/local/lib/python3.8/distutils/log.py", line 46, in info
        self._log(INFO, msg, args)
      File "/usr/local/lib/python3.8/distutils/log.py", line 31, in _log
        stream.write('%s\n' % msg)
      File "/usr/local/lib/python3.8/codecs.py", line 378, in write
        self.stream.write(data)
    TypeError: write() argument must be str, not bytes
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
root@4f07de037284:/#
